name: ✏️ New depoiment
description: Add a depoiment to my profile readme
title: "Type your depoiment below to add it to my profile"
labels: ["Depoiment"]

body:
  - type: textarea
    id: issue_body
    attributes:
      label: "Your depoiment"
      description: "Write the depoiment that will be added to the profile readme."
      placeholder: "Write your depoiment here..."
    validations:
      required: true
      min_length: 10