name: Add Issue Content to README

on:
  issues:
    types: [opened]

jobs:
  update-readme:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: read

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Add content to readme
        run: |
          ISSUE_BODY=$(echo "${{ github.event.issue.body }}" | awk '/### Your depoiment/{flag=1; next} flag' | sed '1{/^$/d;}')
          ISSUE_AUTHOR=$(jq -r .issue.user.login "$GITHUB_EVENT_PATH")
          USER_DATA=$(curl -s "https://api.github.com/users/${ISSUE_AUTHOR}")
          AVATAR_URL=$(echo "$USER_DATA" | jq -r .avatar_url)
          BIO=$(echo "$USER_DATA" | jq -r .bio)
          
          if [ "$BIO" == "null" ] || [ -z "$BIO" ]; then
            BIO=""
          fi

          LANGUAGE=$(echo "${{ github.event.issue.body }}" | grep -A 1 "### Depoiment language" | tail -n 1 | tr -d '\r')
          if [ "$LANGUAGE" == "EN-US" ]; then
            FLAG="🇺🇸"
          else
            FLAG="🇧🇷"
          fi
          
          echo -e "|![${ISSUE_AUTHOR}](${AVATAR_URL}&s=48)  | *${ISSUE_BODY}* |" >> README.md
          echo -e "|--|--|" >> README.md
          echo -e "| ${FLAG} | @${ISSUE_AUTHOR} <br> *${BIO}* |" >> README.md

      - name: commit and push changes
        run: |
          git config --global user.name 'brunoannunciato'
          git config --global user.email 'brunobannunciato@gmail.com'

          git add README.md

          ISSUE_NUMBER=$(jq -r .issue.number "$GITHUB_EVENT_PATH")
          git commit -m ":sparkles: new depoiment added from issue #${ISSUE_NUMBER}"

          git push
