name: Add Issue Content to README

on:
  issues:
    types: [opened]

jobs:
  update-readme:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Repository checkout
        uses: actions/checkout@v4

      - name: Add content to readme
        run: |
          ISSUE_BODY=$(echo "${{ github.event.issue.body }}" | awk '/### Your depoiment/{flag=1; next} flag' | sed '1{/^$/d;}')
          ISSUE_BODY=$(echo "$ISSUE_BODY" | sed -e 's/|/\\|/g' -e 's/\*/\\*/g' -e 's/"/\\"/g' | sed -e ':a;N;$!ba;s/\n/<br>/g')
          ISSUE_AUTHOR=$(jq -r .issue.user.login "$GITHUB_EVENT_PATH")
          USER_DATA=$(curl -s "https://api.github.com/users/${ISSUE_AUTHOR}")
          AVATAR_URL=$(echo "$USER_DATA" | jq -r .avatar_url)
          BIO=$(echo "$USER_DATA" | jq -r .bio)
          
          if [ "$BIO" == "null" ] || [ -z "$BIO" ]; then
            BIO=""
          fi

          echo -e "|![${ISSUE_AUTHOR}](${AVATAR_URL}&s=48)  | *${ISSUE_BODY}* <br><br> <a href='https://github.com/${ISSUE_AUTHOR}' target='_blank'>@${ISSUE_AUTHOR}</a> <br> *${BIO}* |" >> README.md

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: ":sparkles: new depoiment added from issue #${{ github.event.issue.number }}"
          title: 'New depoiment from @${{ github.event.issue.user.login }}'
          body: |
            This PR adds a new depoiment from @${{ github.event.issue.user.login }}.
            Closes #${{ github.event.issue.number }}
          branch: "depoiment-issue-${{ github.event.issue.number }}"
          base: "main"
          labels: depoiment

      - name: Close issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: "PR created: ${{ steps.cpr.outputs.pull-request-url }}"
